# fly.toml app configuration file generated for pizza-store-broken-water-3534 on 2025-02-25T14:10:18-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pizza-store-broken-water-3534'
primary_region = 'lax'
console_command = '/rails/bin/rails console'

[build]

[[services]]
  protocol = "tcp"
  internal_port = 3000
  [[services.ports]]
    handlers = ["http"]
    port = 80
  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
